# Generated by Django 6.0.2 on 2026-08-20 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POSsystem', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produk',
            name='gambar',
            field=models.ImageField(blank=True, null=True, upload_to='produk_images/'),
        ),
    ]
