# Generated by Django 6.0.2 on 2026-08-20 06:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POSsystem', '0003_transaksi_detailtransaksi'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiwayatStok',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipe', models.CharField(choices=[('MASUK', 'Barang Masuk (Restock)'), ('KELUAR', 'Barang Keluar (Penyesuaian/Rusak)')], max_length=10)),
                ('jumlah', models.IntegerField()),
                ('tanggal', models.DateTimeField(auto_now_add=True)),
                ('keterangan', models.TextField(blank=True, help_text='Contoh: Tambahan dari supplier A, atau Barang rusak', null=True)),
                ('produk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='POSsystem.produk')),
            ],
        ),
    ]
