# Generated by Django 6.1 on 2026-08-23 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POSsystem', '0004_riwayatstok'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaksi',
            name='kembalian',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='transaksi',
            name='uang_dibayar',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
