# Generated by Django 6.1 on 2026-08-23 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POSsystem', '0005_transaksi_kembalian_transaksi_uang_dibayar'),
    ]

    operations = [
        migrations.AddField(
            model_name='produk',
            name='stok_minimum',
            field=models.IntegerField(default=5),
        ),
    ]
