# Generated by Django 6.1 on 2026-08-23 15:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POSsystem', '0008_auditlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='detailtransaksi',
            name='harga_modal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='transaksi',
            name='diskon',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='transaksi',
            name='metode_pembayaran',
            field=models.CharField(choices=[('TUNAI', 'Tunai'), ('QRIS', 'QRIS'), ('TRANSFER', 'Transfer'), ('DEBIT', 'Debit')], default='TUNAI', max_length=20),
        ),
        migrations.AddField(
            model_name='transaksi',
            name='status',
            field=models.CharField(choices=[('SELESAI', 'Selesai'), ('VOID', 'Void')], default='SELESAI', max_length=10),
        ),
        migrations.CreateModel(
            name='ReturTransaksi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jumlah', models.PositiveIntegerField()),
                ('alasan', models.TextField(blank=True)),
                ('tanggal', models.DateTimeField(auto_now_add=True)),
                ('detail', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='POSsystem.detailtransaksi')),
                ('pengguna', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StokOpname',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stok_sistem', models.IntegerField()),
                ('stok_fisik', models.IntegerField()),
                ('selisih', models.IntegerField()),
                ('keterangan', models.TextField(blank=True)),
                ('tanggal', models.DateTimeField(auto_now_add=True)),
                ('pengguna', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('produk', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='POSsystem.produk')),
            ],
        ),
    ]
