# Generated by Django 6.0.2 on 2026-08-23 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POSsystem', '0009_detailtransaksi_harga_modal_transaksi_diskon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaksi',
            name='snap_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='transaksi',
            name='tipe_pembayaran_gateway',
            field=models.CharField(blank=True, help_text='Contoh: qris, gopay, bank_transfer', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='transaksi',
            name='waktu_bayar',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transaksi',
            name='status',
            field=models.CharField(choices=[('SELESAI', 'Selesai'), ('PENDING', 'Menunggu Pembayaran'), ('VOID', 'Void')], default='SELESAI', max_length=10),
        ),
    ]
